controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . c d . . . . . . . 
        . . . . . . . c d . . . . . . . 
        . . . . . . . c d . . . . . . . 
        . . . . . . . c b . . . . . . . 
        . . . . . . . f f . . . . . . . 
        . . . . . . . c 4 . . . . . . . 
        . . . . . . . f f . . . . . . . 
        . . . . . . . e 4 . . . . . . . 
        . . . . . . e e 5 2 . . . . . . 
        . . . . . . e 4 5 2 . . . . . . 
        . . . . . c c c 2 2 2 . . . . . 
        . . . . e e 4 4 4 5 2 2 . . . . 
        . . e f f f c c 2 2 f f 2 2 . . 
        . e e e e 2 2 4 4 4 4 5 4 2 2 . 
        e e e e e e 2 2 4 4 4 5 4 4 2 2 
        e e e e e e 2 2 4 4 4 4 5 4 2 2 
        `, mySprite, 0, -100)
})
let projectile: Sprite = null
let mySprite: Sprite = null
mySprite = sprites.create(img`
    ...bbccccccbb...
    ..bdddddddd1db..
    .bddbbbbbbbbddb.
    .cdb11111111bdc.
    .cbcdbbbbbbdcbc.
    .fbcc111111ccbf.
    .fbcd111111dcbf.
    f66cdd1111ddc66f
    f66ccbbbbbbcc66f
    fcbb33333333bbcf
    fbb3333333333bbf
    fbb3d111111d3bbf
    fbd1111111111dbf
    fdd1111111111ddf
    fdd1111111111ddf
    fdd1111111111ddf
    fdd1111111111ddf
    fdd11dbbbbd11ddf
    cdbbddddddddbbdf
    cbddddddddddddbc
    cddddddddddddddc
    .cccccccccccccc.
    .fbbfbbbbbbfbbf.
    ..ff........ff..
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
mySprite.setPosition(75, 96)
let mySprite2 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fdd111111ddf......
    ......fbdd1111dddf......
    ......fcdbfddfbdbf......
    .......fbcf11fcbfff.....
    .......ffb1111bcfbcf....
    ........fcdb1bdfbbbf....
    .......ffffffffffcf.....
    .....fcb1bcfffff........
    .....f1b1b1ffff.........
    ......ffbff.............
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
mySprite2.setPosition(randint(0, 160), 6)
